# Generated by Django 4.2 on 2023-04-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productModel',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('calories', models.CharField(max_length=10)),
                ('composition', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
            ],
        ),
    ]
