# Generated by Django 4.2 on 2023-04-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_order_product_id_order_products_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_status',
            field=models.CharField(default=1, max_length=2),
            preserve_default=False,
        ),
    ]
