# Generated by Django 4.2 on 2023-04-13 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
    ]
