# Generated by Django 4.2 on 2023-04-13 09:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0011_remove_order_total_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='order',
            new_name='orderModel',
        ),
    ]
